### ISSUE TITLE
ラジオボタンをあやまって押した場合に無効化する方法がない

### ISSUE THREAD

**Issue by Biacco42** [Self-Made-Keyboards-in-Japan/mon-shin-dialog-sample#1]
`現在起きている問題` 配下の問診内容が一部実際には排他的であるものの同時に複数選択できてしまう。また、そうなった場合に未選択状態に戻すことができない。

### 例

- キーを押しても入力されない
    - 全部のキーが反応しない
- 設定と異なるキーが入力される
    - 全部のキーの入力が設定と異なる

が同時に設定できてしまう。

### 期待する動作

排他的な項目が同時に選択できない。または設問に対して「未選択」の選択肢が用意されており手動で修正できる。

### メモ

とりあえず「未選択」状態を追加するのが楽そうではあります。ラジオボタンを入れ子にする手もあるとは思いますが、制御が面倒になりそう。

**Comment by s-show** [comment]
ラジオボタンの選択状態を元に戻すボタンを追加して push しました。

**Comment by Biacco42** [comment]
ありがとうございます！確認しました。

ただ、`現在起きている問題` の `LEDが点灯しない` のところのみ選択解除ボタンがないのは意図的なものでしょうか？

もし問題なければ `LEDが点灯しない` のところにも他の項目と同様の選択解除のボタンをつける PR できるかと思いますが、いかがでしょうか？

**Comment by s-show** [comment]
> ただ、現在起きている問題 の LEDが点灯しない のところのみ選択解除ボタンがないのは意図的なものでしょうか？

意図的なものではなく、単なる漏れです。
投稿文作成機能の作成に合わせて修正します。

**Comment by Biacco42** [comment]
ありがとうございます。修正確認しましたので Close します。
