### ISSUE TITLE
ビルドガイドURL及び参考にしたURLを入力させるようにしたい

### ISSUE THREAD

**Issue by takashiski** [Self-Made-Keyboards-in-Japan/mon-shin-dialog-sample#11]
回答者がビルドガイド探したりどこの手順を参照したのかを確認する作業が負荷が高い状態なので書かせたいです。

ビルドガイド・ビルドログ・QMK導入手順いずれにしてもURLが貼ってあればすぐにそこ見てあたりつけるだけですが、URLがない場合回答者がわざわざ検索して探してくる必要があります。

**Comment by s-show** [comment]
確かにそうですね。
どういう形が良いか検討して修正したいと思います。

**Comment by takashiski** [comment]
1. ビルドガイド
2. 回路図・kicadファイル
3. その他参考にしたURL
4. 
あたりを入れられるようにしたいですね
