### ISSUE TITLE
文言の提案です。

### ISSUE THREAD

**Issue by mtei** [Self-Made-Keyboards-in-Japan/mon-shin-dialog-sample#2]
PCとキーボードの接続方法のところ念の為
 * 有線 --> 有線(USB)

ソケットの使用状況のところ、
 * ソケットの使用状況 --> キースイッチ用のソケットの使用状況
 * ソケットを使用していない --> ソケットを使用せず、キースイッチは半田付け。

遊舎工房のショップでも、コンスルーはこう説明しているので、、、
 * コンスルー --> コンスルー（スプリングピンヘッダ）

**Comment by s-show** [comment]
ご提案の文言の方が分かりやすいと思いますので、修正版を push しました。
