### ISSUE TITLE
現状の質問トレンド？に問診表が対応できてないように感じる

### ISSUE THREAD

**Issue by takashiski** [Self-Made-Keyboards-in-Japan/mon-shin-dialog-sample#25]
色々課題を感じてるのでとりあえず問題提起レベルで起こします。

**Comment by s-show** [comment]
ご指摘いただきありがとうございます。
私も #consultation-room でいくつも追加質問をしないといけない現状を見て、問診票の手直しが必要だと思っていましたので、色々考えたいと思います。
それにあたり、以下の点を確認させていただけると助かります。

> 大規模？販売の半完成品のような非QMKで独自手順が必要で独自文書が用意されているはずのキーボードは先に店舗問い合わせをさせる

この点については、「GBで購入したキーボードは販売元にお問い合わせください」と一律に求めれば良いものでしょうか？
