### ISSUE TITLE
ソケットの種類

### ISSUE THREAD

**Issue by hatanoh** [Self-Made-Keyboards-in-Japan/mon-shin-dialog-sample#3]
現在は
MXソケット
kailhソケット
なっていますが、ソケットのメーカーはどちらも(通常)kailhなのでかなり混乱しました。

kailhはいくつも独自footプリントのスイッチを出していますし、
ソケット(MX)
ソケット(ChocV1)
というようにキースイッチの種類で統一して記述した方が良いと思います。
あるいはcherryMXとkailhChocV1とメーカー＋キースイッチ表記でもよいと思います。

**Comment by s-show** [comment]
これは私の理解不足が原因で、MXスイッチ用のソケットはKailh以外のメーカーが製作し、Chocスイッチ用のソケットをKailhが製作していると思い込んだためです。
今後、Choc V2スイッチ用のソケットが販売された時に備えて、以下のとおり修正しようと思います。

```
ソケット (Cherry MXスイッチ用)
ソケット (Kailh Choc V1スイッチ用)
```

**Comment by takashiski** [comment]
しいていうなら、MX用はGateron製のものが存在している（BTO取り扱い）ので区別したほうがよさそうです。
