### ISSUE TITLE
回答内容にエラーログを含めるとDiscordの1メッセージの文字数制限を超える

### ISSUE THREAD

**Issue by takashiski** [Self-Made-Keyboards-in-Japan/mon-shin-dialog-sample#7]
Discordの文字数制限が2000文字で、それを超えるとtxtファイルとして送るかというダイアログがでます。
これで送信してしまうと、ファイル扱いになりますがプレビュー機能がないため、ダウンロードして開く必要があります。これはWindowsとAndroidで確認しました。

解決策としては以下が考えられます。

1. 2000文字以下目安でコピペエリアを分割する
2. 最終出力が2000文字以下になるまで削減するようにエラーを出す
2. 問診票にエラーログは貼らずに別で添付するように書く
    * あわせて、回答内容に文字数制限を入れる

**Comment by s-show** [comment]
対応策ですが、
1. コピペエリアを分割する方法は、文字数2,000毎にテキストボックスが必要になりますので、ちょっと難しいかなと思います。あらかじめテキストボックスを複数用意しておき、2,000字毎に振り分ける方法も考えられますが、ログだけで6,000字を超えるケース（(https://discord.com/channels/376937950409392130/568074928457252865/793472291568746526)）もありますので、テキストボックスが4つぐらい必要になってちょっと非現実的かなと思います。
2. そのため、2,000字以下になるようエラーを出すか、2,000字ずつ切り取る方法にしようかと思っています。
3. 注意喚起については、「ファームウェアを書き込めない」場合には表示するようにしていますが、(https://discord.com/channels/376937950409392130/568074928457252865/793472291568746526) の方は「ファームウェアをビルドできない」というトラブルで、これに対する選択肢が無いため、「その他の問題」にログを貼り付けたものと思います。<br>これについては、以下のスクショのとおり「ファームウェアをビルドできない」という選択肢を用意し、ログを別途投稿するよう注意喚起を表示するよう改良する予定です。
![image](https://user-images.githubusercontent.com/20755159/110120674-b3687800-7e00-11eb-80fb-60a0b1f631e4.png)

**Comment by s-show** [comment]
上記回答で
> そのため、2,000字以下になるようエラーを出すか、2,000字ずつ切り取る方法にしようかと思っています。

としていましたが、次の2つの理由により「文字数＋行数が2001を超えたらエラーメッセージを出すとともにコピーボタンを使用不可にする」方法で実装しました。
理由ですが、1つ目は、Discord の投稿欄に貼付けする時の制限が「文字数＋行数が2001以内」という非常に判定が難しいものであることと、2つ目は、一定の文字数で切り取っていく方法だと、中途半端な所でぶつ切りになった投稿文になることが予想されるためです。
実際の画面は次のとおりです。
![image](https://user-images.githubusercontent.com/20755159/110239280-74b1f980-7f89-11eb-964e-efec85ba2269.png)
